spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.2.103:3306/data_test
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://192.168.2.103:3306/data_test
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver