druid:
  master:
    url: jdbc:mysql://192.168.2.103:3306/data_test
    username: root
    password: 123456
    driverClass: com.mysql.cj.jdbc.Driver
  slave:
    url: jdbc:mysql://192.168.2.104:3306/data_test
    username: root
    password: 123456
    driverClass: com.mysql.cj.jdbc.Driver